
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=UTF8
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true
        use_sql_comments: true
        format_sql: true
        descriptor:
          sql: trace
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none